packages:
  - name: v1
    functions:
      - name: stories
        runtime: nodejs:18
        web: true
  - name: v2
    functions:
      - name: stories
        runtime: nodejs:18
        web: true
